# Generated by Django 5.0.1 on 2024-04-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinishedJankenGames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.IntegerField(default=-1)),
                ('opponent', models.IntegerField(default=-1)),
                ('owner_choice', models.CharField(max_length=100)),
                ('opponent_choice', models.CharField(max_length=100)),
                ('result', models.CharField(max_length=100)),
                ('completion_time', models.DateTimeField()),
                ('loser', models.IntegerField(default=-1)),
                ('winner', models.IntegerField(default=-1)),
            ],
            options={
                'verbose_name': 'Finished Janken Game',
                'verbose_name_plural': 'Finished Janken Games',
            },
        ),
        migrations.CreateModel(
            name='JankenGameCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.IntegerField(default=-1)),
                ('isWaiting', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Janken Game Creation',
                'verbose_name_plural': 'Janken Game Creations',
            },
        ),
        migrations.CreateModel(
            name='JankenGameInProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.IntegerField(default=-1)),
                ('opponent', models.IntegerField(default=-1)),
                ('creator_choice', models.CharField(default='None', max_length=100)),
                ('opponent_choice', models.CharField(default='None', max_length=100)),
                ('game_finished', models.BooleanField(default=False)),
                ('to_delete_creator', models.BooleanField(default=False)),
                ('to_delete_opponent', models.BooleanField(default=False)),
                ('result', models.CharField(default='None', max_length=100)),
                ('completion_time', models.DateTimeField(blank=True, null=True)),
                ('loser', models.IntegerField(default=-1)),
                ('winner', models.IntegerField(default=-1)),
                ('first_input_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('first_input_nickname', models.IntegerField(default=-1)),
            ],
            options={
                'verbose_name': 'Janken Game In Progress',
                'verbose_name_plural': 'Janken Games In Progress',
            },
        ),
    ]
