{
 "title": "Big Overview",
 "description": "Services up",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Taux de Requêtes HTTP par Seconde",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(django_http_requests_total_by_method_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Etat des services (1 = up, 0 = down)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }
  },
  {
   "title": "Front",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"front\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Auth",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"auth\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pong",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"game\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Janken",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"janken\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Torunament",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"tournament\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prometheus",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"prometheus\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Disponibilite over time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Auth",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(up{job=\"auth\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Front",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(up{job=\"front\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pong",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(up{job=\"game\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Janken",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(up{job=\"janken\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tournament",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(up{job=\"tournament\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prometheus",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(up{job=\"prometheus\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Taux de Requêtes HTTP Total / seconde sur  1 min par methode",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 }
  },
  {
   "title": "GET",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(django_http_requests_total_by_method_total{method=\"GET\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "POST",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(django_http_requests_total_by_method_total{method=\"POST\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Jauge d'Utilisation du CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Front",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"front\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Auth",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"auth\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pong",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"game\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Janken",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"janken\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tournament",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"tournament\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prometheus",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"prometheus\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Utilisation Mémoire", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Memoire utilise par service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Latence des requêtes en seconde",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 }
  },
  {
   "title": "Front",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(django_http_requests_latency_seconds_by_view_method_sum{job=\"front\"}[5m]) / rate(django_http_requests_latency_seconds_by_view_method_count{job=\"front\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Janken",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(django_http_requests_latency_seconds_by_view_method_sum{job=\"janken\"}[5m]) / rate(django_http_requests_latency_seconds_by_view_method_count{job=\"janken\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pong",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(django_http_requests_latency_seconds_by_view_method_sum{job=\"game\"}[5m]) / rate(django_http_requests_latency_seconds_by_view_method_count{job=\"game\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tournament",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(django_http_requests_latency_seconds_by_view_method_sum{job=\"tournament\"}[5m]) / rate(django_http_requests_latency_seconds_by_view_method_count{job=\"tournament\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Auth",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(django_http_requests_latency_seconds_by_view_method_sum{job=\"auth\"}[5m]) / rate(django_http_requests_latency_seconds_by_view_method_count{job=\"auth\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Taux de Response", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "Front 2XX Responses",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(django_http_responses_total_by_status_total{job=\"front\", status=~\"2.+\"}[30s]))"
    }
   ]
  },
  {
   "title": "Front 4XX Responses",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(django_http_responses_total_by_status_total{job=\"front\", status=~\"4.+\"}[30s]))"
    }
   ]
  },
  {
   "title": "Front 5XX Responses",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(django_http_responses_total_by_status_total{job=\"front\", status=~\"5.+\"}[30s]))"
    }
   ]
  },
  {
   "title": "Auth 2XX Responses",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(django_http_responses_total_by_status_total{job=\"auth\", status=~\"2.+\"}[30s]))"
    }
   ]
  },
  {
   "title": "Auth 4XX Responses",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(django_http_responses_total_by_status_total{job=\"auth\", status=~\"4.+\"}[30s]))"
    }
   ]
  },
  {
   "title": "Auth 5XX Responses",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(django_http_responses_total_by_status_total{job=\"auth\", status=~\"5.+\"}[30s]))"
    }
   ]
  },
  {
   "title": "Pong 2XX Responses",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(django_http_responses_total_by_status_total{job=\"game\", status=~\"2.+\"}[30s]))"
    }
   ]
  },
  {
   "title": "Pong 4XX Responses",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(django_http_responses_total_by_status_total{job=\"game\", status=~\"4.+\"}[30s]))"
    }
   ]
  },
  {
   "title": "Pong 5XX Responses",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(django_http_responses_total_by_status_total{job=\"game\", status=~\"5.+\"}[30s]))"
    }
   ]
  },
  {
   "title": "Janken 2XX Responses",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(django_http_responses_total_by_status_total{job=\"janken\", status=~\"2.+\"}[30s]))"
    }
   ]
  },
  {
   "title": "Janken 4XX Responses",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(django_http_responses_total_by_status_total{job=\"janken\", status=~\"4.+\"}[30s]))"
    }
   ]
  },
  {
   "title": "Janken 5XX Responses",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(django_http_responses_total_by_status_total{job=\"janken\", status=~\"5.+\"}[30s]))"
    }
   ]
  },
  {
   "title": "Tournament 2XX Responses",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(django_http_responses_total_by_status_total{job=\"tournament\", status=~\"2.+\"}[30s]))"
    }
   ]
  },
  {
   "title": "Tournament 4XX Responses",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(django_http_responses_total_by_status_total{job=\"tournament\", status=~\"4.+\"}[30s]))"
    }
   ]
  },
  {
   "title": "Tournament 5XX Responses",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(django_http_responses_total_by_status_total{job=\"tournament\", status=~\"5.+\"}[30s]))"
    }
   ]
  },
  { "title": "Taux de Requêtes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 } },
  {
   "title": "Front",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(django_http_requests_total_by_method_total{job=\"front\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pong",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(django_http_requests_total_by_method_total{job=\"game\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Auth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(django_http_requests_total_by_method_total{job=\"auth\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Janken",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(django_http_requests_total_by_method_total{job=\"janken\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tournament",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(django_http_requests_total_by_method_total{job=\"tournament\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}