# Generated by Django 5.0.1 on 2024-04-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0002_finishedponggames_tourney_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='tx',
            field=models.CharField(default='None', max_length=300),
        ),
        migrations.DeleteModel(
            name='GameModel',
        ),
    ]
